spring:
  application:
    name: eureka-client
  #安全认证
  security:
    user:
      name: admin
      password: 123456

server:
  port: 9761
  servlet:
    context-path: /eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka-server/eureka/
      #defaultZone: http://admin:123456@localhost:8761/eureka-server1/eureka/,http://admin:123456@localhost:8762/eureka-server2/eureka/ (高可用注册中心)
  instance:
    prefer-ip-address: true


