#Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads : 1000
    min-spare-threads: 30

  port: 8005
  connection-timeout: 5000ms
  servlet:
    context-path: /essays

spring:
  application:
    name: essays

  #格式
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

  #jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  redis:
    open: false                 #是否开启redis缓存 true开启 false关闭
    database: 0
    host: localhost
    port: 6379
    password:                   #密码（默认为空）
    timeout: 6000ms             #连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000    #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        #连接池中的最大空闲连接
        min-idle: 5         #连接池中的最小空闲连接

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

  resources:
    add-mappings: false

  datasource:
    url: jdbc:mysql://139.199.115.242:3306/gumpLab?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
