# 部署两台Eureka服务器并启用registerWithEureka。
# 如果您只想在demo / dev环境中部署，则可以设置eureka.server.renewalPercentThreshold为0.49，因此当您单独启动Eureka服务器时，阈值将为0。
server:
  port: 8761
  servlet:
    context-path: /eureka-server

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  server:
    enable-self-preservation: false # 该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
  client:
    registerWithEureka: false # 当前创建的应用是一个服务注册中心，而不是普通的应用，默认情况下，这个应用会向注册中心（也是它自己）注册它自己，设置为false表示禁止这种默认行为
    fetchRegistry: false # 表示不去检索其他的服务，因为服务注册中心本身的职责就是维护服务实例，它也不需要去检索其他服务
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka-server/eureka/

#清理间隔（单位毫秒，默认是60*1000）
#eureka.server.eviction-interval-timer-in-ms=4000

spring:
  application:
    name: eureka-server
  #安全认证
  security:
    user:
      name: admin
      password: 123456
